### ISSUE TITLE
What happens when contents are too large?

### ISSUE THREAD

**Issue by tremby** [tomhodgins/aspect-ratio-spec#4]
Maybe I'm missing something, but I don't see anything in your spec about what happens when the contents of a container with a set aspect-ratio are too large.

Does the container grow to accommodate, or does the content overflow?

I would have expected to see things like min-aspect-ratio and max-aspect-ratio, to handle the various use cases.

**Comment by tomhodgins** [comment]
I'm not sure about the overflow - I think it should be something where you could decide to let the text overflow (override the height set by `aspect-ratio`) or if it should prefer the `aspect-ratio` height and add scrollbars.

As for `min-aspect-ratio` or `max-aspect-ratio`, I'm not sure this is the right way to go with this. There are already `min-` and `max-` variations of things like `-width` and `-height`, but now that CSS has [native `min()` and `max()` functions](https://drafts.csswg.org/css-values/#calc-notation), doesn't that kind of make these properties obsolete?

Wouldn't `width: 50vw; min-width; 50px` be the same as `width: max(50vw, 50px)`? And it's one step more powerful because you can nest `min()` and `max()` like `width: min(max(10px, 10vw), 50px)` and there isn't any `clamp-width` or `clamp-aspect-ratio`, so what CSS has natively would be more powerful and flexible than adding more `min-` and `max-` properties IMO.

The question I guess would be how to specify the interaction of `aspect-ratio` and `min()` and `max()`. I was thinking that you'd only add `aspect-ratio` when you wanted to define the height based on width, so I wasn't originally thinking about the ability to 'clamp' a scalable element to a specific aspect-ratio. I'll have to think about how to include or exclude this so it makes sense! Thanks for bringing it up :D

**Comment by tremby** [comment]
> Wouldn't `width: 50vw; min-width; 50px` be the same as `width: max(50vw, 50px)`?

I don't think this works in all cases. `min-height`, for example, sets the height of something to the smallest height which is both more or equal to the value given, and more or equal to the height of the element's content. There's no CSS unit for "the height of this element's content", is there?

The use case I have in mind is mostly for grid cells. In this case the width is dictated by the grid, not by any styles on the cell itself. Its width might not be easily expressible in any CSS unit.

For example, consider a grid which has a max-width of 1000px. I want its cells to have a base height of being square, but let them grow vertically if there's a lot of content in any given row.

The grid's container might be wider than 1000px (in which case the grid is 1000px wide) or it might be smaller (in which case the grid will be the same width as the container, less than 1000px). In this case say I know that the grid's columns are each 1fr wide, and there are 4 of them, and I know grid-gap is 25px, and now I want to give a min-height to the cell.

If I can assume that I know the width of the grid's container (let's say it's the full viewport width), I guess I could do `min-height: calc((min(1000px, 100vw) - 3 * 25px) / 4)`. Yuck! What's more, if the grid-gap, max-width, number of columns, etc change based on media queries and that kind of thing I need to have a similar nasty min-height for each configuration. And then what if one particular cell spans more than one column?

What's more, I don't think it's possible at all if I don't know the grid's container's width. Maybe it's part of a flex, for example. 

It'd be nice in this situation to just tell it 'max-aspect-ratio: 1/1`. Since the width is fixed (via the grid), the height will now have to at least equal its width, meaning square or taller.

(One way to do this at present is with [a hack like this one](https://keithjgrant.com/posts/2017/03/aspect-ratios/). This is all well and good in many situations, but it doesn't work all the time. I'm seeing it not work right now for a flex inside a grid cell, for example. I've had to fall back to the old [padding plus absolutely-positioned content hack](https://css-tricks.com/aspect-ratio-boxes/), which has the disadvantage that the content can't grow the container if necessary.)

**Comment by Dan503** [comment]
> There's no CSS unit for "the height of this element's content", is there?

Actually there is. It's called `max-content`.

So you could make it work like this:

```css
.min-aspect-ratio {
  /* max() = whatever value is higher */
  aspect-ratio: max(16/9, max-content);
}

.max-aspect-ratio {
  /* min() = whatever value is lower */
  aspect-ratio: min(16/9, max-content);
}

.fixed-aspect-ratio {
  aspect-ratio: 16 / 9;
}
```

**Comment by Dan503** [comment]
Oh wait It's a bit more complicated because we don't know if `max-content` refers to content height or content width in this scenario.

We would need to write something like this instead:

```css
.min-aspect-ratio {
  aspect-ratio: max(16/9, 100% /max-content);
}

.max-aspect-ratio {
  aspect-ratio: min(16/9, 100% / max-content);
}
```
Yuk 🤢🤮

I'd **much rather** simple `max-aspect-ratio` and `min-aspect-ratio` properties.

```css
.min-aspect-ratio {
  min-aspect-ratio: 16 / 9;
}

.max-aspect-ratio {
  max-aspect-ratio: 16 / 9;
}

.fixed-aspect-ratio {
  aspect-ratio: 16 / 9;
}
```
Much nicer 😊

Max and min aspect ratios should be treated the same way as they are treated in media query ratios for consistency.

That means a tall and narrow aspect ratio is considered small. A short and wide aspect ratio is considered large.
